### ISSUE TITLE
iOS: Unable to execute click tracker manually from Custom Event class for banner

### ISSUE THREAD

**Issue by pm-preety-narvekar** [mopub/mopub-ios-sdk#320]
One line summary of the issue here

In mediation workflow, in order to execute click tracker manually, I added following code in my custom event class for banner ad (which has superclass ```MPBannerCustomEvent```):
```
- (BOOL)enableAutomaticImpressionAndClickTracking {
    return NO;
}
```
and called ```[self.delegate trackClick]``` when ad click occurs.
But the click count is not getting reflected on MoPub's portal.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.12.0

#### Device model and OS Version:
iOS - all devices

#### Xcode Version:
11.0

#### Expected behavior:
Manual click tracker should be executed when```enableAutomaticImpressionAndClickTracking``` is disabled.

#### Observed behavior:
On calling ```[self.delegate trackClick]``` from my custom class, the control goes to ```MPBannerCustomEventAdapter``` class in following method:
```
- (void)trackClick
{
    // unlike `[super trackClick]`, this `trackClick` ensures the click is tracked only once
    if ([self.bannerCustomEvent enableAutomaticImpressionAndClickTracking] && !self.hasTrackedClick) {
        self.hasTrackedClick = YES;
        [super trackClick];
    }
}
```
It looks like, manual click tracker is executed only if the automatic impression/click counting is enabled.

Please note, the similar check is not available in interstitial in ```MPBaseInterstitialAdapter``` class neither does in MoPub Android SDK.

**Comment by chauduyphanvu** [comment]
@pm-preety-narvekar, this issue has been fixed in the [5.12.1 ](https://github.com/mopub/mopub-ios-sdk/blob/master/CHANGELOG.md#version-5121-april-16-2020) release of the MoPub SDK. Please upgrade the SDK and let us know if you continue seeing the issue!

Vu Chau
MoPub Team

**Comment by pm-preety-narvekar** [comment]
Awesome!! Thank you for the information. It is working fine with 5.12.1
